project:
  type: website

website:
  title: "CarringtonProperties.github.io"
  navbar:
    left:
      - about.qmd
      - icon: github
        href: https://github.com/CarringtonProperties/Portfolio
      - icon: linkedin
        href: https://www.linkedin.com/in/danielle-carrington-ms-89163929/
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

